### PR TITLE
[Proto] Initial Phaser port

### LINKED ISSUE #20: [Proto / Experimental] Phaser migration
@dominikandreasseitz Maybe review what is interesting in Phaser to be ported here ?

### PR DESCRIPTION
**Pull request by dominikandreasseitz**
Closes #20

### CODE REVIEW

**Comment by dominikandreasseitz** [comment]
closed cc @madagra

**Comment by Roland-djee** [comment]
@dominikandreasseitz Do you need reviews on this ?

**Comment by dominikandreasseitz** [comment]
@Roland-djee this is just a draft, making this work will take significantly more effort

**Comment by Roland-djee** [comment]
> @Roland-djee this is just a draft, making this work will take significantly more effort

Alright. It is just that I am a bit reluctant in leaving draft PRs hanging but hey, it's not like it's happened in many other places.

**Comment by dominikandreasseitz** [comment]
archiving this again since not a priority at the moment, cc @Roland-djee

**Pull request closed without merging**
